---
default:
  image: "python:3.8"
  before_script:
    - pip3 install 'tox < 3.15'

variables:
  TOXENV: ${CI_JOB_NAME}

.job_template: &job_definition
  script:
  - tox

lint:
  extends: .job_template
style:
  extends: .job_template
sec:
  extends: .job_template
pkg:
  extends: .job_template
py38:
  extends: .job_template
py37:
  image: "python:3.7"
  extends: .job_template
